### ISSUE TITLE
Pass multiple stores to consumer / prop collisions

### ISSUE THREAD

**Issue by sami616** [alexvcasillas/cratebox-react#5]
Would it be feasible to pass multiple stores to a consumer?

ie -  `<Consumer store=['user', 'posts']></Consumer> `

Also is it possible to house injected props in an object named after the `identifier` to avoid overriding props by accident?

So accessing the users name like this `this.props.user.name` instead of `this.props.name`

**Comment by alexvcasillas** [comment]
Hello @sami616

I'm working on that and I might have it released, at last, on Friday due to new changes and improvements in cratebox type system :)

Thanks for opening the issue, I'll keep you updated :)

**Comment by sami616** [comment]
Awesome!

**Comment by alexvcasillas** [comment]
Hello @sami616 !!

I'm back with good new for you :)

Version 1.2.0 it's now up and ready for you to use with the proposed changes :)

You will also have to upgrade cratebox to version 0.7.2 so they will work fine together with the new multi-subscription implementation.

Take a look at a codesandbox example I build for you to ceck the features:
https://codesandbox.io/s/o7rpl3zq19

Thanks once again for the issue, hope to hear back from you.

And if you don't mind I ask the question: How do you find cratebox? Do you find it interesting? Are you using it for some small project or just trying stuff?

Cheers mate!

**Comment by sami616** [comment]
This looks great, Thanks Alex. I stumbled across this on twitter its simplicity is what caught my attention. Great work!

I only built a small codesandbox example too just to test out the library so far.

Will shout if i think of any more improvements 

Thanks again for such a quick turnaround!

**Comment by alexvcasillas** [comment]
Thanks to you, always! : )
